find_package(glfw3 QUIET)
if (glfw3_FOUND)
    message(STATUS "Found glfw3 ${glfw3_VERSION}")
else ()
    message(WARNING "glfw3 not found")
endif ()

find_package(OpenGL QUIET)
if (OpenGL_FOUND)
    message(STATUS "Found OpenGL")
else ()
    message(WARNING "OpenGL not found")
endif ()

find_package(SDL2 QUIET)
if (SDL2_FOUND)
    message(STATUS "Found SDL2 ${SDL2_VERSION}")
else ()
    message(WARNING "SDL2 not found")
endif ()

find_package(SDL3 QUIET)
if (SDL3_FOUND)
    message(STATUS "Found SDL3 ${SDL3_VERSION}")
else ()
    message(WARNING "SDL3 not found")
endif ()

find_package(Vulkan QUIET)
if (Vulkan_FOUND)
    message(STATUS "Found Vulkan ${Vulkan_VERSION}")
else ()
    message(WARNING "Vulkan not found")
endif ()

find_package(Allegro QUIET)
if (Allegro_FOUND)
    message(STATUS "Found Allegro ${Allegro_VERSION}")
else ()
    message(WARNING "Allegro not found")
endif ()

find_package(GLUT QUIET)
if (GLUT_FOUND)
    message(STATUS "Found GLUT ${PC_GLUT_VERSION}")
else ()
    message(WARNING "GLUT not found")
endif ()

if (EMSCRIPTEN)
    if (NOT EMSCRIPTEN_VERSION)
        message(FATAL_ERROR "EMSCRIPTEN_VERSION not found")
    endif ()
    if (EMSCRIPTEN_VERSION VERSION_LESS "3.1.43")
        message(FATAL_ERROR "ImGui requires Emscripten version >= 3.1.43, found ${EMSCRIPTEN_VERSION}")
    endif ()
    set(IMGUI_EMSCRIPTEN_FOUND ON)
    set(IMGUI_EMSCRIPTEN_FOUND ON PARENT_SCOPE)
    message(STATUS "Found emscripten ${EMSCRIPTEN_VERSION}")
else ()
    message(WARNING "emscripten not found. `cmake -DCMAKE_TOOLCHAIN_FILE=emsdk/upstream/emscripten/cmake/Modules/Platform/Emscripten.cmake ...`")
endif ()

if (IMGUI_DAWN_DIR)
    if (EXISTS ${IMGUI_DAWN_DIR}/CMakeLists.txt)
        find_package(VulkanUtilityLibraries QUIET)
        if (VulkanUtilityLibraries_FOUND)
            message(STATUS "Found VulkanUtilityLibraries_FOUND")
        else ()
            message(FATAL_ERROR "VulkanUtilityLibraries is a dependency of Dawn. The version fetched by Dawn is not compatible. `sudo apt install vulkan-utility-libraries-dev`")
        endif ()

        # Dawn wgpu desktop
        set(DAWN_FETCH_DEPENDENCIES ON)

        option(DAWN_FETCH_DEPENDENCIES "Use fetch_dawn_dependencies.py as an alternative to using depot_tools" ON)

        # Dawn builds many things by default - disable things we don't need
        option(DAWN_BUILD_SAMPLES "Enables building Dawn's samples" OFF)
        option(TINT_BUILD_CMD_TOOLS "Build the Tint command line tools" OFF)
        option(TINT_BUILD_DOCS "Build documentation" OFF)
        option(TINT_BUILD_TESTS "Build tests" OFF)
        if (NOT APPLE)
            option(TINT_BUILD_MSL_WRITER "Build the MSL output writer" OFF)
        endif()
        if(WIN32)
            option(TINT_BUILD_SPV_READER "Build the SPIR-V input reader" OFF)
            option(TINT_BUILD_WGSL_READER "Build the WGSL input reader" ON)
            option(TINT_BUILD_GLSL_WRITER "Build the GLSL output writer" OFF)
            option(TINT_BUILD_GLSL_VALIDATOR "Build the GLSL output validator" OFF)
            option(TINT_BUILD_SPV_WRITER "Build the SPIR-V output writer" OFF)
            option(TINT_BUILD_WGSL_WRITER "Build the WGSL output writer" ON)
        endif()

        add_subdirectory("${IMGUI_DAWN_DIR}" "${CMAKE_CURRENT_BINARY_DIR}/dawn" EXCLUDE_FROM_ALL)

        set(IMGUI_DAWN_FOUND ON)
        set(IMGUI_DAWN_FOUND ON PARENT_SCOPE)
        message(STATUS "Found dawn")
    else ()
        message(FATAL_ERROR "IMGUI_DAWN_DIR defined but could not find CMakeLists.txt in ${IMGUI_DAWN_DIR}")
    endif ()
else ()
    message(WARNING "dawn not found.")
endif ()

if (ANDROID_NDK)
    message(STATUS "Found ANDROID_NDK ${CMAKE_ANDROID_NDK_VERSION} at ${ANDROID_NDK}.")
else ()
    message(WARNING "ANDROID_NDK not provided. `cmake -DCMAKE_TOOLCHAIN_FILE=android-ndk/build/cmake/android.toolchain.cmake ...`")
endif ()
