find_package(glfw3 QUIET)
if (glfw3_FOUND)
    message(STATUS "Found glfw3 ${glfw3_VERSION}")
else ()
    message(WARNING "glfw3 not found")
endif ()

find_package(OpenGL QUIET)
if (OpenGL_FOUND)
    message(STATUS "Found OpenGL")
else ()
    message(WARNING "OpenGL not found")
endif ()

find_package(SDL2 QUIET)
if (SDL2_FOUND)
    message(STATUS "Found SDL2 ${SDL2_VERSION}")
else ()
    message(WARNING "SDL2 not found")
endif ()

find_package(SDL3 QUIET)
if (SDL3_FOUND)
    message(STATUS "Found SDL3 ${SDL3_VERSION}")
else ()
    message(WARNING "SDL3 not found")
endif ()

find_package(Vulkan QUIET)
if (Vulkan_FOUND)
    message(STATUS "Found Vulkan ${Vulkan_VERSION}")
else ()
    message(WARNING "Vulkan not found")
endif ()

find_package(Allegro QUIET)
if (Allegro_FOUND)
    message(STATUS "Found Allegro ${Allegro_VERSION}")
else ()
    message(WARNING "Allegro not found")
endif ()

find_package(GLUT QUIET)
if (GLUT_FOUND)
    message(STATUS "Found GLUT ${PC_GLUT_VERSION}")
else ()
    message(WARNING "GLUT not found")
endif ()

if (EMSCRIPTEN)
    if (NOT EMSCRIPTEN_VERSION)
        message(FATAL_ERROR "EMSCRIPTEN_VERSION not found")
    endif ()
    if (EMSCRIPTEN_VERSION VERSION_LESS "3.1.43")
        message(FATAL_ERROR "ImGui requires Emscripten version >= 3.1.43, found ${EMSCRIPTEN_VERSION}")
    endif ()
    set(HAS_IMGUI_EMSCRIPTEN ON)
    set(HAS_IMGUI_EMSCRIPTEN ON PARENT_SCOPE)
    message(STATUS "Found emscripten ${EMSCRIPTEN_VERSION}")
else ()
    message(WARNING "emscripten not found. `cmake -DCMAKE_TOOLCHAIN_FILE=emsdk/upstream/emscripten/cmake/Modules/Platform/Emscripten.cmake ...`")
endif ()

find_package(Dawn QUIET)
if (Dawn_FOUND)
    message(STATUS "Found Dawn")
    set(HAS_IMGUI_DAWN ON)
    set(HAS_IMGUI_DAWN ON PARENT_SCOPE)
else ()
    message(WARNING "Dawn not found")
endif ()

if (ANDROID_NDK)
    message(STATUS "Found ANDROID_NDK ${CMAKE_ANDROID_NDK_VERSION} at ${ANDROID_NDK}.")
else ()
    message(WARNING "ANDROID_NDK not provided. `cmake -DCMAKE_TOOLCHAIN_FILE=android-ndk/build/cmake/android.toolchain.cmake ...`")
endif ()
