
set(FOUND_BACKENDS "")
if (glfw3_FOUND AND OpenGL_FOUND)
    list(APPEND FOUND_BACKENDS "glfw_opengl2" "glfw_opengl3")
endif ()
if (glfw3_FOUND AND Vulkan_FOUND)
    list(APPEND FOUND_BACKENDS "glfw_vulkan")
endif ()
if (SDL2_FOUND AND NOT IMGUI_EMSCRIPTEN_FOUND)
    list(APPEND FOUND_BACKENDS "sdl2_sdlrenderer2")
endif ()
if (SDL2_FOUND AND OpenGL_FOUND)
    list(APPEND FOUND_BACKENDS "sdl2_opengl2" "sdl2_opengl3")
endif ()
if (SDL2_FOUND AND Vulkan_FOUND)
    list(APPEND FOUND_BACKENDS "sdl2_vulkan")
endif ()
if (SDL3_FOUND AND OpenGL_FOUND)
    list(APPEND FOUND_BACKENDS "sdl3_opengl3")
endif ()
if (SDL3_FOUND AND NOT IMGUI_EMSCRIPTEN_FOUND)
    list(APPEND FOUND_BACKENDS "sdl3_sdlgpu3" "sdl3_sdlrenderer3")
endif ()
if (SDL3_FOUND AND Vulkan_FOUND)
    list(APPEND FOUND_BACKENDS "sdl3_vulkan")
endif ()
if (Allegro_FOUND)
    list(APPEND FOUND_BACKENDS "allegro5")
endif ()
if (GLUT_FOUND AND OpenGL_FOUND)
    list(APPEND FOUND_BACKENDS "glut_opengl2")
endif ()
if (IMGUI_EMSCRIPTEN_FOUND)
    list(APPEND FOUND_BACKENDS "glfw_wgpu_emscripten" "glfw_opengl3_emscripten" "sdl2_opengl3_emscripten" "sdl3_opengl3_emscripten")
endif ()
if (IMGUI_DAWN_FOUND AND glfw3_FOUND)
    list(APPEND FOUND_BACKENDS "glfw_wgpu_dawn")
endif ()
if (IMGUI_EMSCRIPTEN_FOUND AND glfw3_FOUND AND OpenGL_FOUND)
    list(APPEND FOUND_BACKENDS "glfw_web_opengl3")
endif ()
if (ANDROID_NDK)
    list(APPEND FOUND_BACKENDS "android_opengl3")
endif ()

set(SUPPORTED_BACKENDS ${FOUND_BACKENDS})
set(SUPPORTED_BACKENDS ${FOUND_BACKENDS} PARENT_SCOPE)
message(STATUS "Supported backends ${SUPPORTED_BACKENDS}")
